# Disable the blank line at the start of the prompt
add_newline = false

[character]
disabled = false
success_symbol = '[](color_green)'
error_symbol = '[](color_red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "